### ISSUE TITLE
The implemention of the interface in this project includes the interface itself

### ISSUE THREAD

**Issue by xtudouh** [ian-kent/go-log#8]
type Logger interface {
	Level() levels.LogLevel
	Name() string
	FullName() string
        ...
}
type logger struct {
	Logger
	level       levels.LogLevel
	name        string
	enabled     map[levels.LogLevel]bool
	appender    Appender
	children    []Logger
	parent      Logger
	ExitOnFatal bool
}
In the type logger,  Logger is if unnecessary or not.

**Comment by ian-kent** [comment]
thanks @xtudouh
